### ISSUE TITLE
Call is in reverse order with selector, index

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#7] opened 2016-01-24 19:27 UTC
`parseExpr "x.f(2)"`
Expected:
`Right (Call (Selector (Variable "x") "f") (NormalArguments [Literal (IntLit 2)]))`
Actual:
`Right (Selector (Call (Variable "x") (NormalArguments [Literal (IntLit 2)])) "f")`

Below, an example of a "real" program with expected behavior

``` go
package main

import "fmt"

type Foo struct {
  val int
}

func (f Foo) print(x int) {
  fmt.Println(f.val + x)
}

func main() {
  f := Foo{2}
  f.print(2) //Prints 4
}
```

**Comment by lafrancef** [comment] 2016-01-24 19:27
Note that `(x.f)(2)` parses fine.

**Comment by lafrancef** [comment] 2016-01-24 19:30
Same issue with index: `fs[0](a)` gives `Right (Index (Call (Variable "fs") (NormalArguments [Variable "a"])) (Literal (IntLit 0)))` instead of `Right (Call (Index (Variable "fs") (Literal (IntLit 0))) (NormalArguments [Variable "a"]))`

**Comment by tsani** [comment] 2016-01-24 19:32
Duplicate of #6

**Closed as completed** 2016-01-24 19:32 UTC
Labels: bug, duplicate
